### ISSUE TITLE
OSX and py36

### ISSUE THREAD

**Issue by dfroger** [conda-forge/waf-feedstock#5]
There is not package for OSX and Python 3.6 (https://anaconda.org/conda-forge/waf/files).

**Comment by nicoddemus** [comment]
Thanks for the ping. Restarting OSX build, hopefully that will fix this.

**Comment by nicoddemus** [comment]
https://travis-ci.org/conda-forge/waf-feedstock

**Comment by dfroger** [comment]
@nicoddemus thanks!

**Comment by dfroger** [comment]
That's fixed with the rebuild, thanks!

**Comment by nicoddemus** [comment]
Wow that was quick. 😁 

Thanks!
